//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swd.TimeManager.GuiMaui.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swd.TimeManager.GuiMaui.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string lblDuration {
            get {
                return ResourceManager.GetString("lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry date.
        /// </summary>
        internal static string lblEntrydate {
            get {
                return ResourceManager.GetString("lblEntrydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit date.
        /// </summary>
        internal static string lblExitdate {
            get {
                return ResourceManager.GetString("lblExitdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string lblFirstname {
            get {
                return ResourceManager.GetString("lblFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string lblLastname {
            get {
                return ResourceManager.GetString("lblLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string lblPerson {
            get {
                return ResourceManager.GetString("lblPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblPersonName {
            get {
                return ResourceManager.GetString("lblPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string lblProject {
            get {
                return ResourceManager.GetString("lblProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string lblProjectname {
            get {
                return ResourceManager.GetString("lblProjectname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string lblSum {
            get {
                return ResourceManager.GetString("lblSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string lblTask {
            get {
                return ResourceManager.GetString("lblTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string lblTaskname {
            get {
                return ResourceManager.GetString("lblTaskname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timerecord.
        /// </summary>
        internal static string lblTimerecordname {
            get {
                return ResourceManager.GetString("lblTimerecordname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail or Username.
        /// </summary>
        internal static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string MenTitleOverview {
            get {
                return ResourceManager.GetString("MenTitleOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        internal static string MenTitlePerson {
            get {
                return ResourceManager.GetString("MenTitlePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string MenTitleProject {
            get {
                return ResourceManager.GetString("MenTitleProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string MenTitleSearchList {
            get {
                return ResourceManager.GetString("MenTitleSearchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenTitleSettings {
            get {
                return ResourceManager.GetString("MenTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string MenTitleTask {
            get {
                return ResourceManager.GetString("MenTitleTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time record.
        /// </summary>
        internal static string MenTitleTimeRecord {
            get {
                return ResourceManager.GetString("MenTitleTimeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string PageTitleLogin {
            get {
                return ResourceManager.GetString("PageTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string PageTitleOverview {
            get {
                return ResourceManager.GetString("PageTitleOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person add.
        /// </summary>
        internal static string PageTitlePersonAdd {
            get {
                return ResourceManager.GetString("PageTitlePersonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person delete.
        /// </summary>
        internal static string PageTitlePersonDelete {
            get {
                return ResourceManager.GetString("PageTitlePersonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person edit.
        /// </summary>
        internal static string PageTitlePersonEdit {
            get {
                return ResourceManager.GetString("PageTitlePersonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        internal static string PageTitlePersonList {
            get {
                return ResourceManager.GetString("PageTitlePersonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project add.
        /// </summary>
        internal static string PageTitleProjectAdd {
            get {
                return ResourceManager.GetString("PageTitleProjectAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project delete.
        /// </summary>
        internal static string PageTitleProjectDelete {
            get {
                return ResourceManager.GetString("PageTitleProjectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project edit.
        /// </summary>
        internal static string PageTitleProjectEdit {
            get {
                return ResourceManager.GetString("PageTitleProjectEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string PageTitleProjectList {
            get {
                return ResourceManager.GetString("PageTitleProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string PageTitleSearchList {
            get {
                return ResourceManager.GetString("PageTitleSearchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task add.
        /// </summary>
        internal static string PageTitleTaskAdd {
            get {
                return ResourceManager.GetString("PageTitleTaskAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task delete.
        /// </summary>
        internal static string PageTitleTaskDelete {
            get {
                return ResourceManager.GetString("PageTitleTaskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task edit.
        /// </summary>
        internal static string PageTitleTaskEdit {
            get {
                return ResourceManager.GetString("PageTitleTaskEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string PageTitleTaskList {
            get {
                return ResourceManager.GetString("PageTitleTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add Timerecord.
        /// </summary>
        internal static string PageTitleTimeRecordAdd {
            get {
                return ResourceManager.GetString("PageTitleTimeRecordAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete Timerecord.
        /// </summary>
        internal static string PageTitleTimeRecordDelete {
            get {
                return ResourceManager.GetString("PageTitleTimeRecordDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit Timerecord.
        /// </summary>
        internal static string PageTitleTimeRecordEdit {
            get {
                return ResourceManager.GetString("PageTitleTimeRecordEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time record.
        /// </summary>
        internal static string PageTitleTimeRecordList {
            get {
                return ResourceManager.GetString("PageTitleTimeRecordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record your time.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account?.
        /// </summary>
        internal static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request account information from your Administrator.
        /// </summary>
        internal static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeManager.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
